Main_fragment
Aristman/Ruen pull request #5
Opened 2022-04-04 21:34 UTC by AnuytkaPoova

Добрый день.
Добавила макеты экранов:
fragment_main - главный экран 
fragment_word_of_day - экран для карточки дня (пока картинка)
item_history - экран для спика истории переводов
Поправила activity_main

2022-04-06 04:18 UTC, zamyatinmn requested changes

2022-04-06 04:18 UTC, zamyatinmn commented on app/build.gradle.kts
> +    implementation("androidx.navigation:navigation-ui-ktx:2.4.1")
Для чего эти зависимости? Они уже подключены в проект

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/values/style.xml
> +        <item name="android:textColor">#80FFFFFF</item>
Цвета стоит вынести в отдельный файл colors, а здесь ссылаться на них. Альфа канал лучше применять отдельно.

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/values/style.xml
> +        <item name="android:textSize">17.28sp</item>
Про размеры у нас был холивар на работе.. суть в том чтобы использовать только четные значения размеров, тем более текста. И уж точно не дробные. Это может влиять на отображение текста. К сожалению, пруфов нет

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/values/strings.xml
> +    <string name="write_the_word">Write the word</string>
На сколько мне известно, артикль `the` подразумевает написание какого-то одного конкретного слова

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/values/strings.xml
> +    <string name="rus">RUS</string>
Касательно нейминга - имя должно отображать функцию, которая скрывается за этой сущностью. Например в данном случае это может быть query_language

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/values/strings.xml
> +    <string name="freedom">Freedom</string>
Технический текст, который нужен только для разработчика выносить в ресурсы не нужно

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/values/dimens.xml
> +    <dimen name="width_48">48dp</dimen>
Особенно остро вопрос нейминга здесь встает. От таких переменных нет никакого смысла. Нужно четко обозначать размер чего вынесен сюда, на каком экране. Это должна быть логическая единица.
Ее размером можно удобно управлять через ресурсы вручную, либо с помощью квалификаторов. В таком виде это никуда не годится.

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/menu/bottom_nav_menu.xml
> -        android:id="@+id/navigationSituations"
Зачем переименовала? Айдишник пункта меню должен быть идентичным с айдишником элемента в графе навигации, если сильно хочется переименовать, делать это нужно в двух местах

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/item_history.xml
> +<?xml version="1.0" encoding="utf-8"?>
Для этого макета использовать ConstraintLayout избыточно, он больше ресурсов отъедает у системы, а смысла в нем тут нет. Идеально подойдет LinearLayout

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/item_history.xml
> +        app:layout_constraintTop_toBottomOf="parent" />
Весь этот код можно заменить одной строчкой в TextView - background

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/item_history.xml
> +        android:layout_marginLeft="@dimen/margin_8"
Начиная с 17 API следует использовать вместо left и right - start и end. Это необходимо для корректного отображения в rtl макетах, например в арабских странах. Даже если не планируется поддержка этих стран

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/item_history.xml
> +        android:layout_marginBottom="@dimen/margin_16"
В таком случае удобно использовать `layout_marginVertical`

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/item_history.xml
> +        android:gravity="center_horizontal|center_vertical"
Можно написать просто `center`

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/item_history.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Я бы сделал как-то так
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="horizontal">

    <TextView
        android:id="@+id/word"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginVertical="@dimen/history_vertical_spacing"
        android:layout_weight="1"
        android:background="@drawable/ic_history_eng_background"
        android:gravity="center"
        android:textAppearance="@style/freedom"
        tools:text="@string/freedom" />

    <TextView
        android:id="@+id/translate_word"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginVertical="@dimen/history_vertical_spacing"
        android:layout_weight="1"
        android:background="@drawable/ic_history_rus_background"
        android:gravity="center"
        android:textAppearance="@style/some_id"
        tools:text="@string/freedom_translate" />

</LinearLayout>
```

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/fragment_word_of_day.xml
> +<?xml version="1.0" encoding="utf-8"?>
Тут что-то совсем странное, что мы хотим получить от этого макета? Почему всё из картинок?

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/fragment_main.xml
> +            android:background="@drawable/ic_launcher_name" />
Этого не должно быть здесь, для логотипа нужно в main activity создать appBarLayout

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/fragment_main.xml
> +        tools:targetApi="s">
Для чего этот лейаут?

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/fragment_main.xml
> +            android:background="@drawable/ic_menu_translate" />
В 100% случаев это плохая идея.
Фон можно указать через background. Можно сразу иконку с фоном сделать.

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/fragment_main.xml
> +        </FrameLayout>
Если мы хотим использовать этот FrameLayout как контейнер для фрагмента, зачем поверх него `<include layout="@layout/fragment_word_of_day" />`? А если не хотим, тогда зачем тут FrameLayout?

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/fragment_main.xml
> +            <TextView
Внутри CardView, если необходимо использовать несколько элементов, лучше их положить в контейнер. Так как CardView наследник FrameLayout, он подразумевает одного потомка. В данном случае, если увеличить размер текста, дописать что-то , текст заползет под RecyclerView

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/fragment_main.xml
> +    <com.google.android.material.bottomnavigation.BottomNavigationView
Этому здесь тоже не место, и это уже реализовано в activity_main

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/layout/activity_main.xml
> +<!--
Это надо вернуть, иначе ветка даже не компилируется

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/drawable/ic_launcher_search.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Для этих целей подойдет лучше `<shape>`

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/drawable/ic_launcher_search.xml
> +<?xml version="1.0" encoding="utf-8"?>
Почему у всех картинок префикс launcher?

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/drawable/ic_launcher_item_1.xml
> +<vector
Отдельный файл, из которого нужен только цвет для фона. Зачем он?

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/drawable/ic_launcher_btn.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Тут я бы наверное использовал png. В векторе эта картинка сильно отличается от исходной

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/drawable/ic_launcher_background_word_day.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
То же самое, лучше пнг

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/drawable/bottom.xml
> +<?xml version="1.0" encoding="utf-8"?>
Посмотри `bottom_nav_shape` и сравни. Предназначение у этих файлов одинаковое

2022-04-06 04:18 UTC, zamyatinmn commented on app/src/main/res/drawable/background.xml
> +<?xml version="1.0" encoding="utf-8"?>
Это тоже делается с помощью shape

2022-04-06 17:44 UTC, AnuytkaPoova commented on app/src/main/res/values/strings.xml
> +    <string name="write_the_word">Write the word</string>
Согласна, и гугл подтвердил ))

2022-04-06 17:47 UTC, AnuytkaPoova commented on app/build.gradle.kts
> +    implementation("androidx.navigation:navigation-ui-ktx:2.4.1")
Я их не добавляла, очень странно. Но исключила на всякий случай.

2022-04-06 17:47 UTC, AnuytkaPoova commented on app/src/main/res/values/style.xml
> +        <item name="android:textColor">#80FFFFFF</item>
Вынесла все цвета в colors. размеры в dimen

2022-04-06 17:47 UTC, AnuytkaPoova commented on app/src/main/res/values/style.xml
> +        <item name="android:textSize">17.28sp</item>
Сделала целые числа у всех размеров

2022-04-06 17:47 UTC, AnuytkaPoova commented on app/src/main/res/values/strings.xml
> +    <string name="rus">RUS</string>
Поправила

2022-04-06 17:49 UTC, AnuytkaPoova commented on app/src/main/res/values/strings.xml
> +    <string name="freedom">Freedom</string>
Поправила

2022-04-06 18:09 UTC, AnuytkaPoova commented on app/src/main/res/layout/activity_main.xml
> +<!--
вернула

2022-04-06 18:14 UTC, AnuytkaPoova commented on app/src/main/res/layout/fragment_main.xml
> +        </FrameLayout>
Я не знаю чего мы хотим, мы не обсудили что делаем с карточкой слово дня. Решили вроде что не успеем карточку слово дня написать. Поэтому  я не стала на первом экране просто картинку вставлять, а создала отдельный макет fragment_word_of_day к нему сделала ссылку, чтобы можно было потом изменить только отдельный макет. Напиши что сделать я сделаю., сама не понимаю как лучше.

2022-04-06 18:15 UTC, AnuytkaPoova commented on app/src/main/res/layout/fragment_main.xml
> +        tools:targetApi="s">
Я не знаю чего мы хотим, мы не обсудили что делаем с карточкой слово дня. Решили вроде что не успеем карточку слово дня написать. Поэтому я не стала на первом экране просто картинку вставлять, а создала отдельный макет fragment_word_of_day к нему сделала ссылку, чтобы можно было потом изменить только отдельный макет. Напиши что сделать я сделаю., сама не понимаю как лучше.

2022-04-06 18:18 UTC, AnuytkaPoova commented on app/src/main/res/layout/item_history.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Там есть еще цветовой фон для слова и перевода отдельный. Мне кажется у меня не сильно отличается. Предлагаю оставить как есть.

2022-04-06 18:21 UTC, AnuytkaPoova commented on app/src/main/res/drawable/ic_launcher_btn.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Ты сам говорил что png нельзя использовать. Пусть так останется. не плохо же выглядит и так.

2022-04-06 18:21 UTC, AnuytkaPoova commented on app/src/main/res/drawable/ic_launcher_background_word_day.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Ты сам говорил что png нельзя использовать. Пусть так останется. не плохо же выглядит и так.

2022-04-06 18:50 UTC, AnuytkaPoova commented on app/src/main/res/layout/item_history.xml
> +        app:layout_constraintTop_toBottomOf="parent" />
не поняла что нужно сделать

2022-04-06 18:51 UTC, AnuytkaPoova commented on app/src/main/res/layout/item_history.xml
> +<?xml version="1.0" encoding="utf-8"?>
запомнила, но наше приложение не большое, справится, оставлю пока так, для экономии времени.

2022-04-06 18:53 UTC, AnuytkaPoova commented on app/src/main/res/values/dimens.xml
> +    <dimen name="width_48">48dp</dimen>
изменила

2022-04-06 18:54 UTC, AnuytkaPoova commented on app/src/main/res/layout/item_history.xml
> +        android:layout_marginLeft="@dimen/margin_8"
исправила

2022-04-06 18:55 UTC, AnuytkaPoova commented on app/src/main/res/layout/item_history.xml
> +        android:gravity="center_horizontal|center_vertical"
исправила

2022-04-06 18:57 UTC, AnuytkaPoova commented on app/src/main/res/layout/item_history.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
По дизайну для слова  и перевода есть еще цветовой фон  который у меня как View вставлен. Предлагаю оставить как есть , будет время потом переделаю.

2022-04-06 19:02 UTC, AnuytkaPoova commented on app/src/main/res/layout/fragment_main.xml
> +        tools:targetApi="s">
Для общей структуры, если уберу вся ориентация всех макетов полетит, придется начинать заново все делать

2022-04-06 19:04 UTC, AnuytkaPoova commented on app/src/main/res/drawable/bottom.xml
> +<?xml version="1.0" encoding="utf-8"?>
Разные, я пробовала и то и то вставлять

2022-04-06 19:06 UTC, AnuytkaPoova commented on app/src/main/res/drawable/background.xml
> +<?xml version="1.0" encoding="utf-8"?>
Я не знаю как через shape это сделать , У меня есть только код vector. Все остальное нужно сидеть разбираться. Предлагаю оставить пока так, потом исправлю как будет время.

2022-04-06 19:08 UTC, AnuytkaPoova commented on app/src/main/res/drawable/ic_launcher_item_1.xml
> +<vector
Это не фон а vector.  У меня есть только код vector. Все остальное нужно сидеть разбираться. Предлагаю оставить пока так, потом исправлю как будет время.

2022-04-06 19:09 UTC, AnuytkaPoova commented on app/src/main/res/drawable/ic_launcher_search.xml
> +<?xml version="1.0" encoding="utf-8"?>
Поправила

2022-04-06 19:13 UTC, AnuytkaPoova commented on app/src/main/res/menu/bottom_nav_menu.xml
> -        android:id="@+id/navigationSituations"
Я делала по дизайну. Мы же вроде ситуации решили не делать так как не успеем. Разве нет?

2022-04-06 19:15 UTC, AnuytkaPoova commented on app/src/main/res/layout/fragment_main.xml
> +            android:background="@drawable/ic_menu_translate" />
Фон из vectora потому ч то не могу там просто цвет фона вставить

2022-04-06 19:33 UTC, AnuytkaPoova commented on app/src/main/res/layout/fragment_main.xml
> +            android:background="@drawable/ic_launcher_name" />
Логотип оказывается сделал Филипп, Я тогда это удалю у себя

2022-04-06 19:35 UTC, AnuytkaPoova commented on app/src/main/res/menu/bottom_nav_menu.xml
> -        android:id="@+id/navigationSituations"
Я делала по дизайну. Мы же вроде ситуации решили не делать так как не успеем. Наверное вообще стоит удалить мои изменения по меню?

2022-04-07 03:48 UTC, zamyatinmn commented on app/build.gradle.kts
> +    implementation("androidx.navigation:navigation-ui-ktx:2.4.1")
Нужно удалять, а ты закомментировала. Закомментированного кода не должно быть в принципе в главной ветке

2022-04-07 03:51 UTC, zamyatinmn commented on app/src/main/res/values/strings.xml
> +    <string name="rus">RUS</string>
Речь была не про эту строку, а вообще про все)

2022-04-07 03:52 UTC, zamyatinmn commented on app/src/main/res/values/strings.xml
> +    <string name="freedom">Freedom</string>
Не все убрала

2022-04-07 03:53 UTC, zamyatinmn commented on app/src/main/res/values/dimens.xml
> +    <dimen name="width_48">48dp</dimen>
А остальное?)

2022-04-07 03:58 UTC, zamyatinmn commented on app/src/main/res/layout/item_history.xml
> +<?xml version="1.0" encoding="utf-8"?>
Я же тебе скинул целиком код этого макета)

2022-04-07 03:59 UTC, zamyatinmn commented on app/src/main/res/layout/item_history.xml
> +        app:layout_constraintTop_toBottomOf="parent" />
Ты создаешь отдельную сущность на экране только для того, чтобы отобразить фон. Но это можно и нужно делать через атрибут `background`

2022-04-07 04:02 UTC, zamyatinmn commented on app/src/main/res/layout/item_history.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Да, и он реализован этой строчкой `android:background="@drawable/ic_history_eng_background"`

2022-04-07 04:04 UTC, zamyatinmn commented on app/src/main/res/layout/fragment_main.xml
> +            android:background="@drawable/ic_launcher_name" />
Опять таки, удалять нужно, а не комментировать

2022-04-07 05:18 UTC, zamyatinmn commented on app/src/main/res/layout/fragment_main.xml
> +        tools:targetApi="s">
А для чего он изначально был добавлен?

2022-04-07 05:20 UTC, zamyatinmn commented on app/src/main/res/drawable/ic_launcher_item_1.xml
> +<vector
Посмотришь потом, как сделал я

2022-04-07 05:21 UTC, zamyatinmn commented on app/src/main/res/drawable/ic_launcher_btn.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Вектор неспособен отобразить некоторые картинки, в данном случае это не иконка, а растровая картинка и при конвертации в вектор, она теряет детализацию.

2022-04-07 06:05 UTC, zamyatinmn commented on app/src/main/res/menu/bottom_nav_menu.xml
> -        android:id="@+id/navigationSituations"
На счет ситуаций не знаю, пока что пусть висят, решим, когда к завершению будет близиться

2022-04-07 06:47 UTC, zamyatinmn approved these changes

2022-04-07 07:24 UTC, 23err approved these changes

2022-04-07 07:25 UTC, merged