2-й экран
Aristman/Ruen pull request #7
Opened 2022-04-07 21:09 UTC by Vekyork

Сделал 2-й экран.
Прошу посмотреть.
Жду замечаний. Готов оперативно исправить недостатки.

2022-04-08 18:48 UTC, 23err commented on app/build.gradle.kts
> +    implementation("androidx.recyclerview:recyclerview:1.2.1")
implementation("com.google.android.material:material:1.5.0")
    implementation("androidx.cardview:cardview:1.0.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.3")
    implementation("androidx.recyclerview:recyclerview:1.2.1")
Все они уже установлены в проекте, можно удалить

2022-04-08 18:51 UTC, 23err commented on app/src/main/res/layout/android_lar_2.xml
> +    <RelativeLayout
Зачем в contraintlayout помещать relative? contraint это улучшенная версия Relative. Можно использовать только его. Если удобнее RelativeLayout, тогда лучше удалить constraint

2022-04-08 18:51 UTC, 23err commented on app/src/main/res/layout/android_lar_2.xml
> +            android:layout_width="141dp"
все размеры должны быть вынесены в ресурсы

2022-04-08 18:51 UTC, 23err commented on app/src/main/res/layout/android_lar_2.xml
> +            tools:ignore="MissingConstraints" />
Зачем игнорировать предупреждение?

2022-04-08 18:53 UTC, 23err commented on app/src/main/res/layout/android_lar_2.xml
> +        <FrameLayout
Почему выбрал FrameLayout? у тебя много элементов в нем и элементы от размера экрана будут наезжать друг на друга

2022-04-08 18:53 UTC, 23err commented on app/src/main/res/layout/android_lar_2.xml
> +                android:id="@+id/_2"
по id не понятно что за поле

2022-04-08 18:54 UTC, 23err commented on app/src/main/res/layout/android_lar_2.xml
> +                android:text="@string/V"
Что такое V?

2022-04-08 18:54 UTC, 23err commented on app/src/main/res/layout/android_lar_2.xml
> +        tools:layout_editor_absoluteY="820dp" />
absolute значений не должно быть

2022-04-08 18:56 UTC, Vekyork commented
А что выбрать вместо него?08.04.2022, 21:53, "23err" ***@***.***>:
@23err commented on this pull request.



In app/src/main/res/layout/android_lar_2.xml:
> +            android:id="@+id/word_to_translate"
+            android:layout_width="178dp"
+            android:layout_height="50dp"
+            android:layout_alignStart="@+id/rus"
+            android:layout_alignParentTop="true"
+            android:layout_marginStart="62dp"
+            android:layout_marginTop="168dp"
+            android:background="#0fff0000"
+            android:gravity="center_horizontal|center_vertical"
+            ***@***.***/word_to_translate"
+            ***@***.***/word_to_translate"
+            tools:ignore="MissingConstraints">
+
+        </FrameLayout>
+
+        <FrameLayout

Почему выбрал FrameLayout? у тебя много элементов в нем и элементы от размера экрана будут наезжать друг на друга

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- 

2022-04-08 18:57 UTC, Vekyork commented
Это жирная 2 на экране перевода08.04.2022, 21:54, "23err" ***@***.***>:
@23err commented on this pull request.



In app/src/main/res/layout/android_lar_2.xml:
> +                android:gravity="center_horizontal|center_horizontal|center_vertical"
+                ***@***.***/property"
+                ***@***.***/property" />
+
+            <TextView
+                android:id="@+id/second_description"
+                android:layout_width="280dp"
+                android:layout_height="50dp"
+                android:layout_marginStart="20dp"
+                android:layout_marginTop="167dp"
+                android:gravity="center_horizontal|center_horizontal|center_vertical"
+                ***@***.***/second_description"
+                ***@***.***/second_description" />
+
+            <TextView
+                android:id="@+id/_2"

по id не понятно что за поле

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- 

2022-04-08 18:59 UTC, zamyatinmn requested changes

2022-04-08 18:59 UTC, zamyatinmn commented on app/build.gradle.kts
> +    implementation("androidx.recyclerview:recyclerview:1.2.1")
Почти все эти зависимости уже подключены в проекте
А те, которых нет, необходимо описывать в классе Dependencies

2022-04-08 18:59 UTC, zamyatinmn commented on app/src/main/res/values/dimens.xml
> +    <dimen name="V">18sp</dimen>
Что за имена? Через неделю даже автор не разберется что это

2022-04-08 18:59 UTC, zamyatinmn commented on app/src/main/res/values/icon_ruen.xml
> +<?xml version="1.0" encoding="utf-8"?>
Пустой файл, для чего он?

2022-04-08 18:59 UTC, zamyatinmn commented on app/src/main/res/values-night/strings.xml
> +    <string name="poisk">poisk</string>
Необходимо избегать транслитерации

2022-04-08 18:59 UTC, zamyatinmn commented on app/src/main/res/layout/android_lar_2.xml
> +<?xml version="1.0" encoding="utf-8"?>
Этот макет нужно полностью переделать

2022-04-08 20:56 UTC, Vekyork reviewed
Прошу посмотреть

2022-04-08 21:03 UTC, 23err commented on app/src/main/res/layout/android_lar_2.xml
> +        android:layout_width="178dp"
Все значения надо вынести в ресурсы по всем view

2022-04-08 21:04 UTC, 23err commented on app/src/main/res/layout/android_lar_2.xml
> +<RelativeLayout
Лучше все-таки использовать constraintLayout, relative уже устарел

2022-04-08 21:05 UTC, 23err commented on app/src/main/res/layout/android_lar_2.xml
> +        android:layout_width="62dp"
ширина и высота редко задается конкретными параметрами. Т.к. на разных экранах может растягиваться и наоборот

2022-04-08 21:06 UTC, 23err commented on app/src/main/res/layout/android_lar_2.xml
> +    <View
За что эта view отвечает?

2022-04-09 12:41 UTC, Vekyork commented on app/src/main/res/layout/android_lar_2.xml
> +        android:layout_width="62dp"
что тогда поставить вместо параметров ширины, высоты и привязки к Start и Top?

2022-04-09 17:11 UTC, Vekyork commented on app/src/main/res/layout/android_lar_2.xml
> +    <View
Эта view отвечает за отображение логотипа

2022-04-09 17:12 UTC, Vekyork commented on app/src/main/res/layout/android_lar_2.xml
> +<RelativeLayout
constraintLayout пробовал - всё плывет.

2022-04-09 17:12 UTC, Vekyork commented on app/src/main/res/layout/android_lar_2.xml
> +        android:layout_width="178dp"
Исправил

2022-04-09 17:13 UTC, Vekyork commented on app/src/main/res/layout/android_lar_2.xml
> +<?xml version="1.0" encoding="utf-8"?>
Полностью переделал макет

2022-04-09 17:13 UTC, Vekyork commented on app/src/main/res/values-night/strings.xml
> +    <string name="poisk">poisk</string>
Удалил poisk, везде search

2022-04-09 17:13 UTC, Vekyork commented on app/src/main/res/values/icon_ruen.xml
> +<?xml version="1.0" encoding="utf-8"?>
Удалил

2022-04-09 17:14 UTC, Vekyork commented on app/src/main/res/values/dimens.xml
> +    <dimen name="V">18sp</dimen>
V удалил
_1 и _2 это 1 и 2 в блоке перевода с разными вариантами перевода

2022-04-09 17:14 UTC, Vekyork commented on app/build.gradle.kts
> +    implementation("androidx.recyclerview:recyclerview:1.2.1")
Удалил

2022-04-09 17:17 UTC, Vekyork commented on app/src/main/res/layout/android_lar_2.xml
> +        android:layout_width="62dp"
Это ширина и высота конкретного блока. Как иначе. Я готов сразу переделать для многопользовательской версии. ПРОШУ уточнить - чем заменить ширину и высоту.

2022-04-10 05:46 UTC, Aristman commented on app/src/main/res/values/dimens.xml
> +    <dimen name="V">18sp</dimen>
Нейминг ниочем. Нужно все имена переменных давать осмысленными и понятными

2022-04-17 07:36 UTC, closed without merging